import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'
import Header from '@/components/header/Header'

const montserrat = Montserrat({
    variable: '--font-geist-sans',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Receip app',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en'>
            <body
                className={`${montserrat.variable}  antialiased max-w-screen`}
            >
                <div className='w-full flex justify-center'>
                    <Header />
                </div>
                <main>{children}</main>
            </body>
        </html>
    )
}
